### PR TITLE
refactored, execution message, fallback to include, extracted code to…

### PR DESCRIPTION
**Pull request by akorchyn**
## Summary by CodeRabbit

- **New Features**
  - Introduced new `PullRequestFinalize` and `PullRequestMerge` structs for handling pull request finalization and merging.
  - Added `UnknownCommand` handling for unrecognized commands.
  - Added new functions for managing unfinalized and stale pull requests.

- **Bug Fixes**
  - Improved error handling and messaging for already merged pull requests.
  - Ensured only maintainers can pause the bot.

- **Refactor**
  - Consolidated PR-related data structures into a new `shared-types` module.
  - Streamlined import and export of common types across modules.
  - Simplified function parameters by replacing individual fields with structured data types.

- **Chores**
  - Updated workspace and dependencies configuration in `Cargo.toml` files.

### CODE REVIEW

**Comment by race-of-sloths** [comment]
This pull request is a part of Sloth race now.

**Comment by akorchyn** [comment]
@race-of-sloths scor 5

**Comment by race-of-sloths** [comment]
Hey, I'm sorry, but I can't process that: Unexpected command

**Comment by akorchyn** [comment]
@race-of-sloths score 13

**Comment by race-of-sloths** [comment]
Hey, I'm sorry, but I can't process that: Score should be a fibonacci number: 1, 2, 3, 5, 8, or 13.

**Comment by akorchyn** [comment]
@race-of-sloths score 13

**Comment by race-of-sloths** [comment]
Hey, I'm sorry, but I can't process that: You can't score your own PR.

**Comment by race-of-sloths** [comment]
The PR has been merged, but it was not scored. The score process will be closed after 24 hours automatically.

**Comment by race-of-sloths** [comment]
🎉 Hooray! The PR has been finalized. Thank you for your epic contribution! The scoring process is now officially closed. 🏁✨

**Pull request merged**
