### PR TITLE
Fix streak bug

### PR DESCRIPTION
**Pull request by akorchyn**

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
⚠️ Oops! The PR is already merged. It's too late to include us now. Better luck next time! 🚀

**Comment by akorchyn** [comment]
test, 
near-protocol-near-logo

**Comment by akorchyn** [comment]
test,

**Comment by akorchyn** [comment]
user-icon

**Comment by akorchyn** [comment]
user-icon

**Comment by akorchyn** [comment]
user-icon

**Pull request merged**
