### PR TITLE
Variants for bot replies

### PR DESCRIPTION
**Pull request by akorchyn**
## Summary by CodeRabbit

- **New Features**
  - Introduced randomized message responses for various bot commands to enhance user interaction.

- **Improvements**
  - Enhanced error and status messages for pull request actions, making them more informative and varied.

- **Bug Fixes**
  - Refined error handling and reply mechanisms for better accuracy and user feedback.

- **Refactor**
  - Updated message constants to arrays for more flexible and dynamic message selection.
  - Streamlined method calls and message handling across multiple command implementations.

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths INCLUDE

**Comment by race-of-sloths** [comment]
#### ### 🏆 Race of Sloths Status Update 🏆

Hey there! 🎉 Your PR is now part of the Race of Sloths. Thanks for contributing! 🙌

**Current Status:**

- **Scoring:** No one has scored your PR yet. Maintainers can score using `@race-of-sloths score [1,2,3,5,8,13]`.
- **Merge Status:** Your PR hasn't been tracked as merged yet. Hang tight, it might take a bit of time! ⏳
- **Execution Status:** The PR hasn't been executed yet. Stay tuned! 👀

We'll keep this status updated as things progress. Thanks again for your awesome contribution! 🌟

**Comment by akorchyn** [comment]
@race-of-sloths score 5

**Comment by race-of-sloths** [comment]
#### 🚫 No self-scoring allowed! Nice try though. 😉

**Comment by akorchyn** [comment]
@race-of-sloths score 5

**Comment by race-of-sloths** [comment]
#### ❌ Self-scoring is not permitted. Let's keep it fair! 👍

**Comment by race-of-sloths** [comment]
#### ⚡ The PR is merged! Note: it wasn't scored. The scoring process will end in 24 hours. 🕛

**Comment by race-of-sloths** [comment]
#### 🎊 Woohoo! The PR has been completed. Thanks for your fantastic contribution! The scoring process is now done. 🏆

**Pull request merged**
