### PR TITLE
fixed expandable block. Like comment on an error too

### PR DESCRIPTION
**Pull request by akorchyn**

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
⚡ The PR is merged! Note: it wasn't scored. The scoring process will end in 24 hours. 🕛

**Comment by race-of-sloths** [comment]
🎊 Woohoo! The PR has been completed. Thanks for your fantastic contribution! The scoring process is now done. 🏆

**Pull request merged**
