### PR TITLE
Implemented first version of svg

### PR DESCRIPTION
**Pull request by akorchyn**

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Hello, Maintainer! 👋 @akorchyn has submitted another valuable pull request in the Race of Sloths. We appreciate their continued efforts to enhance the project. Your review will help further their contribution's impact.

<details>
<summary>Learn more about the race and how your feedback drives our community forward.</summary>

Use `@race-of-sloths reject` to exclude this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to award points, or `@race-of-sloths pause` to stop my notifications for your repository. For more on how the race runs and our scoring nuances, check out this [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
<svg width="653" height="202" viewBox="0 0 653 202" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<rect width="653" height="202" fill="#0D1116"/>
<rect x="24" y="16" width="32" height="32" rx="15.4622" fill="#30363D"/>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" font-weight="bold" letter-spacing="0em"><tspan x="66" y="36.3636">Vikas Ganiga</tspan></text>
<rect x="24" y="64" width="51" height="23" rx="4" fill="white" fill-opacity="0.1"/>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" font-weight="bold" letter-spacing="0em"><tspan x="32" y="79.8636">3,234</tspan></text>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" font-weight="500" letter-spacing="0em"><tspan x="85" y="79.8636">Total contributions</tspan></text>
<text fill="white" fill-opacity="0.5" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" letter-spacing="0em"><tspan x="197" y="79.8636">with the Race of Sloth</tspan></text>
<rect x="36.625" y="113.5" width="24" height="24" fill="url(#pattern0_66_1159)"/>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="24" letter-spacing="0em"><tspan x="62.625" y="134.227">12,323</tspan></text>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" font-weight="bold" letter-spacing="0em"><tspan x="66.125" y="155.864">Total Score</tspan></text>
<text fill="white" fill-opacity="0.5" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" letter-spacing="0em"><tspan x="47.625" y="174.864">with Race of Sloth</tspan></text>
<path d="M175.25 111L175.25 178" stroke="#30363D" stroke-linecap="round"/>
<rect x="205.875" y="113.5" width="24" height="24" fill="url(#pattern1_66_1159)"/>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="24" letter-spacing="0em"><tspan x="231.875" y="134.227">123</tspan></text>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" font-weight="bold" letter-spacing="0em"><tspan x="234.375" y="155.864">Place</tspan></text>
<text fill="white" fill-opacity="0.5" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" letter-spacing="0em"><tspan x="194.875" y="174.864">Global Leaderboard</tspan></text>
<path d="M326.5 111L326.5 178" stroke="#30363D" stroke-linecap="round"/>
<rect x="370.125" y="113.5" width="24" height="24" fill="url(#pattern2_66_1159)"/>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="24" letter-spacing="0em"><tspan x="396.125" y="134.227">8</tspan></text>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" font-weight="bold" letter-spacing="0em"><tspan x="364.625" y="155.864">Week Streak</tspan></text>
<text fill="white" fill-opacity="0.5" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" letter-spacing="0em"><tspan x="347.625" y="174.864">Sloth Pull Requests</tspan></text>
<path d="M477.75 111L477.75 178" stroke="#30363D" stroke-linecap="round"/>
<rect x="520.875" y="113.5" width="24" height="24" fill="url(#pattern3_66_1159)"/>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="24" letter-spacing="0em"><tspan x="546.875" y="134.227">4</tspan></text>
<text fill="white" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" font-weight="bold" letter-spacing="0em"><tspan x="513.375" y="155.864">Month Streak</tspan></text>
<text fill="white" fill-opacity="0.5" xml:space="preserve" style="white-space: pre" font-family="Inter" font-size="12" letter-spacing="0em"><tspan x="503.875" y="174.864">Hight Valued PR&#x2019;s</tspan></text>
<defs>
<pattern id="pattern0_66_1159" patternContentUnits="objectBoundingBox" width="1" height="1">
<use xlink:href="#image0_66_1159" transform="scale(0.0106383)"/>
</pattern>
<pattern id="pattern1_66_1159" patternContentUnits="objectBoundingBox" width="1" height="1">
<use xlink:href="#image1_66_1159" transform="scale(0.0106383)"/>
</pattern>
<pattern id="pattern2_66_1159" patternContentUnits="objectBoundingBox" width="1" height="1">
<use xlink:href="#image2_66_1159" transform="scale(0.0106383)"/>
</pattern>
<pattern id="pattern3_66_1159" patternContentUnits="objectBoundingBox" width="1" height="1">
<use xlink:href="#image2_66_1159" transform="scale(0.0106383)"/>
</pattern>
<image id="image0_66_1159" width="94" height="94" href="https://github.com/akorchyn.png"/>
</defs>
</svg>

**Comment by race-of-sloths** [comment]
⚡ The PR is merged! Note: it wasn't scored. The scoring process will end in 24 hours. 🕛

**Comment by akorchyn** [comment]
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
  <image href="mdn_logo_only_color.png" height="200" width="200" />
</svg>

**Comment by akorchyn** [comment]
akorchyn (1)

**Comment by race-of-sloths** [comment]
✅ Great job! The PR is finalized. Your contribution is much appreciated. Scoring is now wrapped up! 🎊

**Pull request merged**
