### PR TITLE
Update Cargo.toml

### PR DESCRIPTION
**Pull request by akorchyn**
## Summary by CodeRabbit

- **Chores**
	- Minor formatting improvement in configuration files.

### CODE REVIEW

**Comment by akorchyn** [comment]
@yurturdev start

**Comment by yurturdev** [comment]
Hey hey. You called me ? :).
Keep up the good work akorchyn!
Dear maintainer please score this PR when the time comes to merge it with given syntax `@akorchyn score 1/2/3/4/5. Please note that I will ignore incorrectly provided messages to not spam!

**Comment by akorchyn** [comment]
@yurturdev start

**Comment by yurturdev** [comment]
Hey hey. You called me, @akorchyn? :).
I'm sorry but maintainers and members can't get rewarded for work in their own projects.!

**Comment by akorchyn** [comment]
@yurturdev start

**Comment by yurturdev** [comment]
Hey hey. You called me, @akorchyn? :).
I'm sorry but maintainers and members can't get rewarded for work in their own projects.!

**Comment by akorchyn** [comment]
@yurturdev score 5

**Comment by yurturdev** [comment]
Hey hey.
Thank you for scoring @akorchyn's PR with 5!

**Pull request merged**
