### PR TITLE
Tests and bugfix

### PR DESCRIPTION
**Pull request by akorchyn**
## Summary by CodeRabbit

- **New Features**
  - Introduced test functions for handling GitHub-related operations, scoring, merging, excluding, and finalizing pull requests.
  - Added new methods for interacting with GitHub comments.

- **Bug Fixes**
  - Improved logic for updating streak data.

- **Refactor**
  - Restructured event handling logic for better efficiency and readability.
  - Removed redundant parameters and simplified function signatures.

- **Enhancements**
  - Added new field `best` to `StreakUserData` for enhanced tracking of user streaks.
  - Defined constants for score timeout durations.

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Hey there, Maintainer! 🌟 @akorchyn just contributed another pull request to the Race of Sloths. It’s great to see their ongoing dedication! Please review their work to help advance their standing in the race.

<details>
<summary>Interested in more details about the race and your role in shaping our contributors' paths?</summary>

Here’s what you can do next: Use `@race-of-sloths reject` to remove this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to assign points, or `@race-of-sloths pause` to silence notifications temporarily. For a complete guide on how the Race of Sloths works and our scoring system, click here: [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Hello, Maintainer! 👋 @akorchyn has submitted another valuable pull request in the Race of Sloths. We appreciate their continued efforts to enhance the project. Your review will help further their contribution's impact.

<details>
<summary>Learn more about the race and how your feedback drives our community forward.</summary>

Here’s what you can do next: Use `@race-of-sloths reject` to remove this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to assign points, or `@race-of-sloths pause` to silence notifications temporarily. For a complete guide on how the Race of Sloths works and our scoring system, click here: [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@race-of-sloths exclude

**Comment by race-of-sloths** [comment]
😔 It looks like this pull request has been excluded from the Race of Sloths. We understand it’s disappointing, but every contribution matters, and your participation is highly appreciated.

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Greetings, Maintainer! 🛠️ Here’s another contribution by @akorchyn in the Race of Sloths. Their consistent participation is what keeps our project thriving. Your expert review is crucial for their progress.

<details>
<summary>Click here to dive deeper into how your support impacts our collaborative success.</summary>

Use `@race-of-sloths reject` to exclude this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to award points, or `@race-of-sloths pause` to stop my notifications for your repository. For more on how the race runs and our scoring nuances, check out this [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Greetings, Maintainer! 🛠️ Here’s another contribution by @akorchyn in the Race of Sloths. Their consistent participation is what keeps our project thriving. Your expert review is crucial for their progress.

<details>
<summary>Click here to dive deeper into how your support impacts our collaborative success.</summary>

Here’s what you can do next: Use `@race-of-sloths reject` to remove this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to assign points, or `@race-of-sloths pause` to silence notifications temporarily. For a complete guide on how the Race of Sloths works and our scoring system, click here: [link](https://github.com/race-of-sloths).
</details>

**Comment by race-of-sloths** [comment]
🙁 This pull request has been excluded by the maintainer of the project. We’re truly sorry to see your work not make it this time.

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Hello, Maintainer! 👋 @akorchyn has submitted another valuable pull request in the Race of Sloths. We appreciate their continued efforts to enhance the project. Your review will help further their contribution's impact.

<details>
<summary>Learn more about the race and how your feedback drives our community forward.</summary>

Here’s what you can do next: Use `@race-of-sloths reject` to remove this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to assign points, or `@race-of-sloths pause` to silence notifications temporarily. For a complete guide on how the Race of Sloths works and our scoring system, click here: [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@race-of-sloths exclude

**Comment by race-of-sloths** [comment]
🙁 We're sorry to see this pull request excluded from the Race of Sloths. While it’s sad to see your effort sidelined, we value every contribution and look forward to your future submissions.

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Greetings, Maintainer! 🛠️ Here’s another contribution by @akorchyn in the Race of Sloths. Their consistent participation is what keeps our project thriving. Your expert review is crucial for their progress.

<details>
<summary>Click here to dive deeper into how your support impacts our collaborative success.</summary>

Use `@race-of-sloths reject` to exclude this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to award points, or `@race-of-sloths pause` to stop my notifications for your repository. For more on how the race runs and our scoring nuances, check out this [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@race-of-sloths exclude

**Comment by race-of-sloths** [comment]
😔 It looks like this pull request has been excluded from the Race of Sloths. We understand it’s disappointing, but every contribution matters, and your participation is highly appreciated.

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Greetings, Maintainer! 🛠️ Here’s another contribution by @akorchyn in the Race of Sloths. Their consistent participation is what keeps our project thriving. Your expert review is crucial for their progress.

<details>
<summary>Click here to dive deeper into how your support impacts our collaborative success.</summary>

Use `@race-of-sloths reject` to exclude this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to award points, or `@race-of-sloths pause` to stop my notifications for your repository. For more on how the race runs and our scoring nuances, check out this [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Greetings, Maintainer! 🛠️ Here’s another contribution by @akorchyn in the Race of Sloths. Their consistent participation is what keeps our project thriving. Your expert review is crucial for their progress.

<details>
<summary>Click here to dive deeper into how your support impacts our collaborative success.</summary>

Here’s what you can do next: Use `@race-of-sloths reject` to remove this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to assign points, or `@race-of-sloths pause` to silence notifications temporarily. For a complete guide on how the Race of Sloths works and our scoring system, click here: [link](https://github.com/race-of-sloths).
</details>

**Comment by race-of-sloths** [comment]
🙁 We're sorry to see this pull request excluded from the Race of Sloths. While it’s sad to see your effort sidelined, we value every contribution and look forward to your future submissions.

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Greetings, Maintainer! 🛠️ Here’s another contribution by @akorchyn in the Race of Sloths. Their consistent participation is what keeps our project thriving. Your expert review is crucial for their progress.

<details>
<summary>Click here to dive deeper into how your support impacts our collaborative success.</summary>

Use `@race-of-sloths reject` to exclude this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to award points, or `@race-of-sloths pause` to stop my notifications for your repository. For more on how the race runs and our scoring nuances, check out this [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@coderabbit review

**Comment by akorchyn** [comment]
@coderabbitai review

**Comment by race-of-sloths** [comment]
⚡ The PR is merged! Note: it wasn't scored. The scoring process will end in 24 hours. 🕛

**Comment by race-of-sloths** [comment]
🎊 Woohoo! The PR has been completed. Thanks for your fantastic contribution! The scoring process is now done. 🏆

**Pull request merged**
