### PR TITLE
Update view

### PR DESCRIPTION
**Pull request by akorchyn**

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloth inc

**Comment by akorchyn** [comment]
@race-of-sloths inc

**Comment by race-of-sloths** [comment]
#### 🔄 The PR has been merged. Heads up, it wasn't scored. Scoring will close in 24 hours! 🕰️

**Comment by race-of-sloths** [comment]
#### ✅ Great job! The PR is finalized. Your contribution is much appreciated. Scoring is now wrapped up! 🎊

**Pull request merged**
