### PR TITLE
Replies are more fun

### PR DESCRIPTION
**Pull request by akorchyn**

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths

**Comment by race-of-sloths** [comment]
This pull request is a part of Sloth race now.

**Comment by race-of-sloths** [comment]
🚀 Woohoo! The PR has been merged, but it wasn't scored. The scoring process will close automatically in 24 hours! ⏳🕒

**Comment by race-of-sloths** [comment]
#### ✅ Great job! The PR is finalized. Your contribution is much appreciated. Scoring is now wrapped up! 🎊

**Pull request merged**
