### PR TITLE
Storage contract & Near client

### PR DESCRIPTION
**Pull request by akorchyn**
## Summary by CodeRabbit

- **New Features**
  - Introduced environment variables for main network checks and secret keys in configuration examples.
  - Enhanced `.gitignore` to cover `.env` files in all subdirectories for better security.
  - Updated workspace configurations and dependencies in `Cargo.toml` files.
  - Added a new smart contract for managing organizations, users, and pull requests with comprehensive methods.
  - Implemented new data structures for user data, organization permissions, and pull requests in the contract.
  - Updated server configurations and Near blockchain interactions in server modules to handle new environment variables and improve blockchain interactions.

- **Bug Fixes**
  - Removed debug print statements from GitHub client notifications and PR merge events to clean up the output.

- **Documentation**
  - Included detailed comments and structured modifications across various configuration and source files to align with new features and updates.

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
This pull request is a part of Sloth race now. Dear maintainer, please use `@race-of-sloths score [1-10]` to rate it, or `@race-of-sloths pause` to stop the sloth for the repository.

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
This pull request is a part of Sloth race now. Dear maintainer, please use `@race-of-sloths score [1-10]` to rate it, or `@race-of-sloths pause` to stop the sloth for the repository.

**Comment by akorchyn** [comment]
@race-of-sloths score 5

**Comment by race-of-sloths** [comment]
Hey, I'm sorry, but I can't process that: Only maintainers can score PRs, and you can't score your own PRs.

**Pull request merged**
