### PR TITLE
fixed issue with waiting for transaction finalization. added status m…

### PR DESCRIPTION
**Pull request by akorchyn**
…essage

### CODE REVIEW

**Comment by race-of-sloths** [comment]
This pull request is a part of Sloth race now.

**Comment by race-of-sloths** [comment]
The PR has been merged, but it was not scored. The score process will be closed after 24 hours automatically.

**Comment by akorchyn** [comment]
@race-of-sloth INclUDE

**Comment by akorchyn** [comment]
@race-of-sloth INclUDE

**Comment by akorchyn** [comment]
@race-of-sloths INclUDE

**Comment by race-of-sloths** [comment]
The PR has been finalized. Thank you for your contribution! The scoring process is closed now.

**Pull request merged**
