### PR TITLE
contract streaks

### PR DESCRIPTION
**Pull request by akorchyn**
## Summary by CodeRabbit

- **New Features**
  - Introduced streak tracking with new data structures and logic to monitor user activity and achievements.
  - Added new time period handling capabilities for more flexible reporting.
  
- **Improvements**
  - Enhanced data mappings for better organization and performance.
  - Restructured module organization for improved code maintainability.

- **Bug Fixes**
  - Updated functions to handle new data structures and improve accuracy in streak calculations.

- **Dependencies**
  - Added new dependencies: `strum` and `chrono` for improved functionality and performance.

- **Removals**
  - Removed outdated functions and dependencies to streamline the codebase.

### CODE REVIEW

**Comment by akorchyn** [comment]
@coderabbitai review

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Greetings, Maintainer! 🛠️ Here’s another contribution by @akorchyn in the Race of Sloths. Their consistent participation is what keeps our project thriving. Your expert review is crucial for their progress.

<details>
<summary>Click here to dive deeper into how your support impacts our collaborative success.</summary>

Here’s what you can do next: Use `@race-of-sloths reject` to remove this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to assign points, or `@race-of-sloths pause` to silence notifications temporarily. For a complete guide on how the Race of Sloths works and our scoring system, click here: [link](https://github.com/race-of-sloths).
</details>

**Comment by race-of-sloths** [comment]
⚡ The PR is merged! Note: it wasn't scored. The scoring process will end in 24 hours. 🕛

**Comment by race-of-sloths** [comment]
🎉 Hooray! The PR has been finalized. Thank you for your epic contribution! The scoring process is now officially closed. 🏁✨

**Pull request merged**
