### PR TITLE
fix v2?

### PR DESCRIPTION
**Pull request by akorchyn**
@race-of-sloths

### CODE REVIEW

**Comment by akorchyn** [comment]
Hello, Awesome Maintainer! 🌟

We're excited to bring you another fantastic contribution by @akorchyn in the Race of Sloths! 🦥 Their relentless participation keeps our project bustling with activity. Your expert review is vital for their journey.

<details>
<summary>Curious about the impact of your support? Click here to find out more! 🚀</summary>

Your next steps are simple: 
- Use `@race-of-sloths reject` to remove this PR from the race,
- Use `@race-of-sloths score [1/2/3/5/8/13]` to assign points,
- Or use `@race-of-sloths pause` to silence notifications temporarily.

For a complete guide on the Race of Sloths and our scoring system, check this out: [link](https://github.com/race-of-sloths).

Your involvement makes a huge difference. Thanks for being awesome! 🙌
</details>

**Comment by akorchyn** [comment]
## 🎉 Hey There, Awesome Maintainer! 🎉

We're over the moon to bring you another **fantastic contribution** by **@akorchyn** in the **Race of Sloths**! 🦥✨ Their relentless participation keeps our project buzzing with excitement. Your expert review is the magic that propels them forward.

<details>
<summary><strong>🤔 Do you want to know something about @akorchyn? Click to find out! 🌟</strong></summary>

**He’s an awesome guy!** Here's some cool info about him:
- 📈 Over the past months, he has contributed **X PRs**.
- 🔥 He's currently on a **streak of 8 months** with at least 2 contributions each month.
- 🏆 He’s in the **top 50 of our contributors**!

Your contribution as a maintainer helps him stay on track in our journey and motivates him to keep up the great work! 🚀
</details>

<details>
<summary><strong>🔍 Curious about the impact of your support? Click here to discover more! 🔍</strong></summary>

**Here's how you can play your part:**
- 🛑 **Reject this PR:** `@race-of-sloths reject` to send this PR back to the drawing board.
- ⭐ **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
- 🔕 **Pause notifications:** `@race-of-sloths pause` to temporarily mute notifications.

Want to know all the ins and outs of the Race of Sloths and our scoring system? Check out our [super fun guide](https://github.com/race-of-sloths). 🎮📚

**Why Your Involvement Matters:**
Your feedback not only helps @akorchyn grow but also fuels the collaborative spirit of our community. Together, we make magic happen! ✨

Thanks for being a rockstar! 🌟🙌

Sloth Image
</details>

**Comment by race-of-sloths** [comment]
❗ Command not recognized. Please verify and give it another shot. 🔄

**Comment by race-of-sloths** [comment]
❓ Hmmm, unknown command. Please check the command and try again. 🕵️‍♂️

**Comment by race-of-sloths** [comment]
🚀 Woohoo! The PR has been merged, but it wasn't scored. The scoring process will close automatically in 24 hours! ⏳🕒

**Comment by race-of-sloths** [comment]
🎊 Woohoo! The PR has been completed. Thanks for your fantastic contribution! The scoring process is now done. 🏆

**Pull request merged**
