### PR TITLE
extracted messages into separate file. Got messages from doc

### PR DESCRIPTION
**Pull request by akorchyn**
@race-of-sloths

### CODE REVIEW

**Comment by race-of-sloths** [comment]
Hey there, Maintainer! 🌟 @akorchyn just contributed another pull request to the Race of Sloths. It’s great to see their ongoing dedication! Please review their work to help advance their standing in the race.

<details open>
<summary>Interested in more details about the race and your role in shaping our contributors' paths?</summary>
Use `@race-of-sloths reject` to exclude this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to award points, or `@race-of-sloths pause` to stop my notifications for your repository. For more on how the race runs and our scoring nuances, check out this [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@race-of-sloths score 12

**Comment by race-of-sloths** [comment]
❌ Self-scoring is not permitted. Let's keep it fair! 👍

**Comment by akorchyn** [comment]
@race-of-sloths score 12

**Comment by akorchyn** [comment]
@race-of-sloths score 12

**Comment by race-of-sloths** [comment]
🚫 No self-scoring allowed! Nice try though. 😉

**Comment by race-of-sloths** [comment]
🚀 Woohoo! The PR has been merged, but it wasn't scored. The scoring process will close automatically in 24 hours! ⏳🕒

**Comment by race-of-sloths** [comment]
🎉 Hooray! The PR has been finalized. Thank you for your epic contribution! The scoring process is now officially closed. 🏁✨

**Pull request merged**
