### PR TITLE
Streak bug-fixing

### PR DESCRIPTION
**Pull request by akorchyn**

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
Hello, Maintainer! 👋 @akorchyn has submitted another valuable pull request in the Race of Sloths. We appreciate their continued efforts to enhance the project. Your review will help further their contribution's impact.

<details>
<summary>Learn more about the race and how your feedback drives our community forward.</summary>

Use `@race-of-sloths reject` to exclude this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to award points, or `@race-of-sloths pause` to stop my notifications for your repository. For more on how the race runs and our scoring nuances, check out this [link](https://github.com/race-of-sloths).
</details>

**Comment by race-of-sloths** [comment]
🔄 The PR has been merged. Heads up, it wasn't scored. Scoring will close in 24 hours! 🕰️

**Comment by race-of-sloths** [comment]
🎊 Woohoo! The PR has been completed. Thanks for your fantastic contribution! The scoring process is now done. 🏆

**Pull request merged**
