### PR TITLE
update comment if only something changed

### PR DESCRIPTION
**Pull request by akorchyn**
## Summary by CodeRabbit

- **New Features**
  - Improved event handling for issues and comments with new structures for commands and actions.
  - Introduced `Action` enum for streamlined pull request management (finalize, merge, mark as stale).

- **Bug Fixes**
  - Enhanced logic to conditionally send replies based on repository permissions.

- **Refactor**
  - Consolidated command and action handling for better modularity and maintainability.
  - Reorganized module imports for cleaner code structure.

- **Chores**
  - Removed outdated `commands` module and introduced a comprehensive `events` module.

### CODE REVIEW

**Comment by akorchyn** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
#### ### 🏆 Race of Sloths Status Update 🏆

Hey there! 🎉 Your PR is now part of the Race of Sloths. Thanks for contributing! 🙌

**Current Status:**

- **Scoring:** No one has scored your PR yet. Maintainers can score using `@race-of-sloths score [1,2,3,5,8,13]`.
- **Merge Status:** Your PR hasn't been tracked as merged yet. Hang tight, it might take a bit of time! ⏳
- **Execution Status:** The PR hasn't been executed yet. Stay tuned! 👀

We'll keep this status updated as things progress. Thanks again for your awesome contribution! 🌟

**Comment by race-of-sloths** [comment]
#### 🔄 The PR has been merged. Heads up, it wasn't scored. Scoring will close in 24 hours! 🕰️

**Comment by race-of-sloths** [comment]
#### 🎊 Woohoo! The PR has been completed. Thanks for your fantastic contribution! The scoring process is now done. 🏆

**Pull request merged**
